name: Build Docker
on: workflow_dispatch
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
permissions:
  packages: write
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Semantic Version
        id: getVersion
        run: |
          export VER=$(jq -r '.version' package.json)

          if ${{ contains(github.ref, 'main') }}; then
            echo "version=$VER" >> $GITHUB_OUTPUT
            echo "latest=latest" >> $GITHUB_OUTPUT
          else
            echo "version=$VER-dev" >> $GITHUB_OUTPUT
            echo "latest=$( git rev-parse --short HEAD )" >> $GITHUB_OUTPUT
          fi
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.getVersion.outputs.version }}
            type=raw,value=${{ steps.getVersion.outputs.latest }}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  auto-version:
    if: github.ref == 'refs/heads/main'
    needs: publish-docker
    uses: ./.github/workflows/auto-version.yaml
    secrets: inherit
    permissions:
      contents: write